
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hzvysykldafzyywlaske.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6dnlzeWtsZGFmenl5d2xhc2tlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MzgyNTUsImV4cCI6MjA2MjExNDI1NX0.yhXMJBoUaX1jFmDtVyiVev7IQ5Wbk7E9DJ_RdZKpqLc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper function to update the types DB
export const updateSupabaseTypes = async () => {
  // This function is a placeholder for type generation in a real implementation
  console.log("Types would be updated from database schema");
};
